all:
  vars:
    ansible_python_interpreter: /usr/bin/python3

  children:
    control_plane:
      hosts:
        ubuntuvm1:
          ansible_connection: local

    workers:
      hosts:
        ubuntuvm2:
          ansible_host: 10.0.2.6
          ansible_user: khash1
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_ansible
