apiVersion: v1
kind: Secret
metadata:
  name: gitlab-ci-deployer-token
  namespace: opsboard
  annotations:
    kubernetes.io/service-account.name: gitlab-ci-deployer
type: kubernetes.io/service-account-token
