{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: opsboard

spec:
  serviceName: db
  replicas: {{ .Values.postgres.replicaCount }}

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: opsboard

    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}

          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}

          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgres.database.user | quote }}

            - name: POSTGRES_DB
              value: {{ .Values.postgres.database.name | quote }}

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.database.user }}
            initialDelaySeconds: {{ .Values.postgres.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.readinessProbe.periodSeconds }}

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.postgres.database.user }}
            initialDelaySeconds: {{ .Values.postgres.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgres.livenessProbe.periodSeconds }}

          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}

  volumeClaimTemplates:
    - metadata:
        name: postgres-data

      spec:
        accessModes:
          - {{ .Values.postgres.persistence.accessMode }}

        storageClassName: {{ .Values.postgres.persistence.storageClass }}

        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}

---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: opsboard

spec:
  type: {{ .Values.postgres.service.type }}

  selector:
    app: postgres

  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}
